generatorName: ada
outputDir: samples/client/petstore/ada
inputSpec: modules/openapi-json-schema-generator/src/test/resources/2_0/petstore.yaml
templateDir: modules/openapi-json-schema-generator/src/main/resources/Ada
additionalProperties:
  modelPackage: Samples.Petstore
  projectName: Petstore
