generatorName: ada
outputDir: samples/client/petstore/ada
inputSpec: src/test/resources/2_0/petstore.yaml
templateDir: src/main/resources/Ada
additionalProperties:
  modelPackage: Samples.Petstore
  projectName: Petstore
