generatorName: avro-schema
outputDir: samples/openapi3/schema/petstore/avro-schema
inputSpec: modules/openapi-json-schema-generator/src/test/resources/3_0/avro-schema/petstore.yaml
templateDir: modules/openapi-json-schema-generator/src/main/resources/avro-schema
