generatorName: cpp-pistache-server
outputDir: samples/server/petstore/cpp-pistache
inputSpec: src/test/resources/2_0/petstore.yaml
templateDir: src/main/resources/cpp-pistache-server
additionalProperties:
  useStructModel: "false"
  addExternalLibs: "true"
