generatorName: cpp-ue4
outputDir: samples/client/petstore/cpp-ue4
inputSpec: modules/openapi-json-schema-generator/src/test/resources/2_0/petstore.yaml
templateDir: modules/openapi-json-schema-generator/src/main/resources/cpp-ue4
