generatorName: cpp-tiny
outputDir: samples/client/petstore/cpp-tiny
inputSpec: modules/openapi-json-schema-generator/src/test/resources/3_0/petstore.yaml
templateDir: modules/openapi-json-schema-generator/src/main/resources/cpp-tiny
additionalProperties:
  hideGenerationTimestamp: "true"
  controller: "esp32"
