generatorName: csharp-netcore-functions
outputDir: samples/client/petstore/csharp-netcore-functions
inputSpec: src/test/resources/3_0/petstore.yaml
templateDir: src/main/resources/csharp-netcore-functions
#additionalProperties:
#  packageGuid: '{321C8C3F-0156-40C1-AE42-D59761FB9B6C}'
