generatorName: cwiki
outputDir: samples/documentation/cwiki
inputSpec: modules/openapi-json-schema-generator/src/test/resources/3_0/petstore.yaml
templateDir: modules/openapi-json-schema-generator/src/main/resources/confluenceWikiDocs
