generatorName: elixir
outputDir: samples/client/petstore/elixir
inputSpec: src/test/resources/3_0/petstore-with-fake-endpoints-models-for-testing.yaml
templateDir: src/main/resources/elixir
additionalProperties:
  invokerPackage: OpenapiPetstore
