generatorName: elm
outputDir: samples/openapi3/client/elm
inputSpec: modules/openapi-json-schema-generator/src/test/resources/3_0/elm.yaml
templateDir: modules/openapi-json-schema-generator/src/main/resources/elm
