generatorName: erlang-client
outputDir: samples/client/petstore/erlang-client
inputSpec: modules/openapi-json-schema-generator/src/test/resources/3_0/petstore.yaml
templateDir: modules/openapi-json-schema-generator/src/main/resources/erlang-client
additionalProperties:
  packageName: petstore
