generatorName: erlang-client
outputDir: samples/client/petstore/erlang-client
inputSpec: src/test/resources/3_0/petstore.yaml
templateDir: src/main/resources/erlang-client
additionalProperties:
  packageName: petstore
