generatorName: go
outputDir: samples/openapi3/client/extensions/x-auth-id-alias/go-experimental
inputSpec: src/test/resources/3_0/extensions/x-auth-id-alias.yaml
templateDir: src/main/resources/go
additionalProperties:
  packageName: x_auth_id_alias
