generatorName: go-gin-server
outputDir: samples/server/petstore/go-gin-api-server
inputSpec: src/test/resources/3_0/petstore.yaml
templateDir: src/main/resources/go-gin-server
additionalProperties:
  hideGenerationTimestamp: "true"
  packageName: petstoreserver
