generatorName: go
outputDir: samples/client/petstore/go/go-petstore
inputSpec: src/test/resources/2_0/petstore-with-fake-endpoints-models-for-testing.yaml
templateDir: src/main/resources/go
additionalProperties:
  packageName: petstore
  generateInterfaces: true
