generatorName: go
outputDir: samples/openapi3/client/petstore/go/go-petstore
inputSpec: src/test/resources/3_0/go/petstore-with-fake-endpoints-models-for-testing-with-http-signature.yaml
templateDir: src/main/resources/go
additionalProperties:
  enumClassPrefix: "true"
  packageName: petstore
  disallowAdditionalPropertiesIfNotPresent: false
  generateInterfaces: true
