generatorName: groovy
outputDir: samples/client/petstore/groovy
inputSpec: modules/openapi-json-schema-generator/src/test/resources/3_0/petstore.yaml
templateDir: modules/openapi-json-schema-generator/src/main/resources/Groovy
additionalProperties:
  hideGenerationTimestamp: "true"
