generatorName: groovy
outputDir: samples/client/petstore/groovy
inputSpec: src/test/resources/3_0/petstore.yaml
templateDir: src/main/resources/Groovy
additionalProperties:
  hideGenerationTimestamp: "true"
