generatorName: haskell-yesod
outputDir: samples/server/petstore/haskell-yesod
inputSpec: src/test/resources/3_0/petstore.yaml
templateDir: src/main/resources/haskell-yesod
additionalProperties:
  hideGenerationTimestamp: "true"
