generatorName: html
outputDir: samples/documentation/html.md
inputSpec: modules/openapi-json-schema-generator/src/test/resources/2_0/markdown.yaml
templateDir: modules/openapi-json-schema-generator/src/main/resources/htmlDocs
