generatorName: java
outputDir: samples/client/others/java/okhttp-gson-streaming
library: okhttp-gson
inputSpec: modules/openapi-json-schema-generator/src/test/resources/3_0/streaming.yaml
templateDir: modules/openapi-json-schema-generator/src/main/resources/Java
additionalProperties:
  artifactId: petstore-okhttp-gson
  hideGenerationTimestamp: "true"
  supportStreaming: true
