generatorName: java
outputDir: samples/client/petstore/java/feign
library: feign
inputSpec: src/test/resources/3_0/petstore-with-fake-endpoints-models-for-testing.yaml
templateDir: src/main/resources/Java
additionalProperties:
  booleanGetterPrefix: is
  artifactId: petstore-feign
  hideGenerationTimestamp: "true"
