generatorName: java
outputDir: samples/client/petstore/java/google-api-client
library: google-api-client
inputSpec: src/test/resources/2_0/petstore-with-fake-endpoints-models-for-testing.yaml
templateDir: src/main/resources/Java
additionalProperties:
  artifactId: petstore-google-api-client
  hideGenerationTimestamp: "true"
