generatorName: java
outputDir: samples/client/petstore/java/rest-assured
library: rest-assured
inputSpec: src/test/resources/2_0/petstore-with-fake-endpoints-models-for-testing.yaml
templateDir: src/main/resources/Java
additionalProperties:
  performBeanValidation: "true"
  useBeanValidation: "true"
  booleanGetterPrefix: is
  artifactId: petstore-rest-assured
  hideGenerationTimestamp: "true"
