generatorName: java
outputDir: samples/client/petstore/java/okhttp-gson-parcelableModel
library: okhttp-gson
inputSpec: src/test/resources/2_0/petstore-with-fake-endpoints-models-for-testing.yaml
templateDir: src/main/resources/Java
additionalProperties:
  parcelableModel: "true"
  artifactId: petstore-okhttp-gson-parcelableModel
  hideGenerationTimestamp: "true"
