generatorName: java
outputDir: samples/client/petstore/java/microprofile-rest-client-3.0
library: microprofile
inputSpec: src/test/resources/3_0/petstore.yaml
templateDir: src/main/resources/Java
additionalProperties:
  artifactId: microprofile-rest-client-3
  configKey: petstore
  microprofileRestClientVersion: "3.0"
