generatorName: java-vertx-web
outputDir: samples/server/petstore/java-vertx-web
inputSpec: src/test/resources/3_0/petstore.yaml
templateDir: src/main/resources/JavaVertXWebServer
additionalProperties:
  hideGenerationTimestamp: "true"
  artifactId: java-vertx-web-server
