generatorName: javascript
outputDir: samples/client/petstore/javascript-apollo
library: apollo
inputSpec: src/test/resources/3_0/javascript/petstore-with-fake-endpoints-models-for-testing.yaml
templateDir: src/main/resources/Javascript
additionalProperties:
  appName: PetstoreClient
