generatorName: java
outputDir: samples/client/petstore/java/retrofit2rx2
library: retrofit2
inputSpec: src/test/resources/2_0/petstore-with-fake-endpoints-models-for-testing.yaml
templateDir: src/main/resources/Java
additionalProperties:
  useRxJava2: "true"
  artifactId: petstore-retrofit2-rx2
  hideGenerationTimestamp: "true"
