generatorName: java-inflector
outputDir: samples/server/petstore/java-inflector
inputSpec: src/test/resources/2_0/petstore-with-fake-endpoints-models-for-testing.yaml
templateDir: src/main/resources/JavaInflector
additionalProperties:
  hideGenerationTimestamp: "true"
