generatorName: java
outputDir: samples/client/petstore/java/vertx
library: vertx
inputSpec: src/test/resources/2_0/petstore-with-fake-endpoints-models-for-testing.yaml
templateDir: src/main/resources/Java
additionalProperties:
  artifactId: petstore-vertx
  hideGenerationTimestamp: "true"
  dateLibrary: java8
