generatorName: java-play-framework
outputDir: samples/server/petstore/java-play-framework-no-bean-validation
inputSpec: src/test/resources/2_0/petstore.yaml
templateDir: src/main/resources/JavaPlayFramework
additionalProperties:
  hideGenerationTimestamp: "true"
  useBeanValidation: "false"
