generatorName: java-undertow-server
outputDir: samples/server/petstore/java-undertow
inputSpec: src/test/resources/2_0/petstore.yaml
templateDir: src/main/resources/java-undertow-server
additionalProperties:
  hideGenerationTimestamp: "true"
