generatorName: java
outputDir: samples/client/petstore/java/resttemplate
library: resttemplate
inputSpec: src/test/resources/2_0/petstore-with-fake-endpoints-models-for-testing.yaml
templateDir: src/main/resources/Java
additionalProperties:
  artifactId: petstore-resttemplate
  hideGenerationTimestamp: "true"
  java8: true
