generatorName: java-play-framework
outputDir: samples/server/petstore/java-play-framework-fake-endpoints
inputSpec: src/test/resources/2_0/petstore-with-fake-endpoints-models-for-testing.yaml
templateDir: src/main/resources/JavaPlayFramework
additionalProperties:
  hideGenerationTimestamp: "true"
