generatorName: java-pkmst
outputDir: samples/server/petstore/java-pkmst
inputSpec: modules/openapi-json-schema-generator/src/test/resources/2_0/petstore.yaml
templateDir: modules/openapi-json-schema-generator/src/main/resources/java-pkmst
additionalProperties:
  hideGenerationTimestamp: "true"
