generatorName: java-play-framework
outputDir: samples/server/petstore/java-play-framework-async
inputSpec: src/test/resources/2_0/petstore.yaml
templateDir: src/main/resources/JavaPlayFramework
additionalProperties:
  supportAsync: true
  hideGenerationTimestamp: "true"
