generatorName: java
outputDir: samples/client/petstore/java/okhttp-gson-dynamicOperations
library: okhttp-gson
inputSpec: src/test/resources/2_0/petstore-with-fake-endpoints-models-for-testing.yaml
templateDir: src/main/resources/Java
additionalProperties:
  artifactId: petstore-okhttp-gson-dynamicoperations
  hideGenerationTimestamp: "true"
  dynamicOperations: "true"
