generatorName: java
outputDir: samples/client/petstore/java/webclient-nulable-arrays
library: webclient
inputSpec: src/test/resources/3_0/schema-with-nullable-arrays.yaml
templateDir: src/main/resources/Java
additionalProperties:
  artifactId: petstore-webclient-nullable-arrays
  hideGenerationTimestamp: "true"
