generatorName: javascript
outputDir: samples/client/petstore/javascript-apollo
library: apollo
inputSpec: modules/openapi-json-schema-generator/src/test/resources/3_0/javascript/petstore-with-fake-endpoints-models-for-testing.yaml
templateDir: modules/openapi-json-schema-generator/src/main/resources/Javascript
additionalProperties:
  appName: PetstoreClient
