generatorName: javascript
outputDir: samples/client/petstore/javascript-promise-es6
library: javascript
inputSpec: src/test/resources/3_0/javascript/petstore-with-fake-endpoints-models-for-testing.yaml
templateDir: src/main/resources/Javascript
additionalProperties:
  usePromises: "true"
  appName: PetstoreClient
