generatorName: java
outputDir: samples/client/petstore/java/jersey2-java8-localdatetime
library: jersey2
inputSpec: src/test/resources/2_0/petstore-with-fake-endpoints-models-for-testing.yaml
templateDir: src/main/resources/Java
additionalProperties:
  artifactId: petstore-jersey2-java8-localdatetime
  hideGenerationTimestamp: "true"
  dateLibrary: java8-localdatetime
  java8: true
  delegatePattern: true
