generatorName: java-msf4j
outputDir: samples/server/petstore/java-msf4j
inputSpec: src/test/resources/2_0/petstore-with-fake-endpoints-models-for-testing.yaml
templateDir: src/main/resources/java-msf4j-server
additionalProperties:
  hideGenerationTimestamp: "true"
  artifactId: java-msf4j-server
