generatorName: java-play-framework
outputDir: samples/server/petstore/java-play-framework-no-wrap-calls
inputSpec: src/test/resources/2_0/petstore.yaml
templateDir: src/main/resources/JavaPlayFramework
additionalProperties:
  hideGenerationTimestamp: "true"
  wrapCalls: "false"
