generatorName: jaxrs-cxf
outputDir: samples/server/petstore/jaxrs-cxf-annotated-base-path
inputSpec: src/test/resources/2_0/petstore.yaml
templateDir: src/main/resources/JavaJaxRS/cxf
additionalProperties:
  artifactId: cxf-annotated-basepath
  hideGenerationTimestamp: "true"
  serverPort: "8082"
  useAnnotatedBasePath: "true"
