generatorName: jaxrs-cxf
outputDir: samples/server/petstore/jaxrs-cxf
inputSpec: src/test/resources/2_0/petstore-with-fake-endpoints-models-for-testing.yaml
templateDir: src/main/resources/JavaJaxRS/cxf
additionalProperties:
  hideGenerationTimestamp: "true"
  serverPort: "8082"
  implicitHeadersRegex: (api_key|enum_header_string)
