generatorName: jaxrs-cxf-client
outputDir: samples/client/petstore/jaxrs-cxf-client
inputSpec: src/test/resources/2_0/petstore.yaml
templateDir: src/main/resources/JavaJaxRS/cxf
additionalProperties:
  artifactId: jaxrs-cxf-petstore-client
