generatorName: jaxrs-resteasy
outputDir: samples/server/petstore/jaxrs-resteasy/java8
inputSpec: src/test/resources/2_0/petstore.yaml
templateDir: src/main/resources/JavaJaxRS/resteasy
additionalProperties:
  artifactId: jaxrs-resteasy-java8-server
  hideGenerationTimestamp: "true"
  dateLibrary: java8
