generatorName: jaxrs-jersey
outputDir: samples/server/petstore/jaxrs/jersey2-useTags
inputSpec: src/test/resources/2_0/petstore-with-fake-endpoints-models-for-testing.yaml
templateDir: src/main/resources/JavaJaxRS
additionalProperties:
  artifactId: jaxrs-jersey2-useTags
  hideGenerationTimestamp: "true"
  serverPort: "8082"
  useTags: "true"
