generatorName: jaxrs-cxf
outputDir: samples/server/petstore/jaxrs-cxf-non-spring-app
inputSpec: modules/openapi-json-schema-generator/src/test/resources/2_0/petstore.yaml
templateDir: modules/openapi-json-schema-generator/src/main/resources/JavaJaxRS/cxf
additionalProperties:
  artifactId: cxf-server-non-spring
  hideGenerationTimestamp: "true"
  generateNonSpringApplication: "true"
  serverPort: "8082"
