generatorName: jaxrs-resteasy
outputDir: samples/server/petstore/jaxrs-resteasy/default
inputSpec: modules/openapi-json-schema-generator/src/test/resources/2_0/petstore.yaml
templateDir: modules/openapi-json-schema-generator/src/main/resources/JavaJaxRS/resteasy
additionalProperties:
  hideGenerationTimestamp: "true"
  implicitHeadersRegex: api_key
