generatorName: jaxrs-resteasy
outputDir: samples/server/petstore/jaxrs-resteasy/default
inputSpec: src/test/resources/2_0/petstore.yaml
templateDir: src/main/resources/JavaJaxRS/resteasy
additionalProperties:
  hideGenerationTimestamp: "true"
  implicitHeadersRegex: api_key
