generatorName: jaxrs-cxf-cdi
outputDir: samples/server/petstore/jaxrs-cxf-cdi
inputSpec: modules/openapi-json-schema-generator/src/test/resources/2_0/petstore.yaml
templateDir: modules/openapi-json-schema-generator/src/main/resources/JavaJaxRS/cxf-cdi
additionalProperties:
  hideGenerationTimestamp: "true"
  implicitHeadersRegex: api_key
