generatorName: jaxrs-resteasy-eap
outputDir: samples/server/petstore/jaxrs-resteasy/eap-joda
inputSpec: src/test/resources/2_0/petstore.yaml
templateDir: src/main/resources/JavaJaxRS/resteasy/eap
additionalProperties:
  artifactId: jaxrs-resteasy-eap-joda-server
  hideGenerationTimestamp: "true"
  dateLibrary: joda
