generatorName: jaxrs-resteasy-eap
outputDir: samples/server/petstore/jaxrs-resteasy/eap
inputSpec: src/test/resources/2_0/petstore.yaml
templateDir: src/main/resources/JavaJaxRS/resteasy/eap
additionalProperties:
  hideGenerationTimestamp: "true"
