generatorName: k6
outputDir: samples/client/petstore/k6
inputSpec: src/test/resources/3_0/petstore-with-fake-endpoints-models-for-testing.yaml
templateDir: src/main/resources/k6
additionalProperties:
  appName: PetstoreClient
