generatorName: kotlin
outputDir: samples/client/petstore/kotlin-default-values-numbers
inputSpec: src/test/resources/3_0/kotlin/issue13506-defaultValue-numbers.yaml
templateDir: src/main/resources/kotlin-client
additionalProperties:
  artifactId: kotlin-default-values-numbers
  serializationLibrary: gson
globalProperties:
  models: ""