generatorName: kotlin
outputDir: samples/client/petstore/kotlin-array-simple-string-jvm-okhttp3
inputSpec: modules/openapi-json-schema-generator/src/test/resources/3_0/issue_7199_array_simple_string.yaml
templateDir: modules/openapi-json-schema-generator/src/main/resources/kotlin-client
additionalProperties:
  artifactId: kotlin-array-simple-string-jvm-okhttp3
  library: jvm-okhttp3
