generatorName: kotlin-spring
outputDir: samples/server/petstore/kotlin-springboot
library: spring-boot
inputSpec: modules/openapi-json-schema-generator/src/test/resources/2_0/petstore.yaml
templateDir: modules/openapi-json-schema-generator/src/main/resources/kotlin-spring
additionalProperties:
  documentationProvider: none
  annotationLibrary: none
  useSwaggerUI: "false"
  serviceImplementation: "true"
  serializableModel: "true"
  beanValidations: "true"
