generatorName: kotlin
outputDir: samples/client/petstore/kotlin-json-request-string
inputSpec: src/test/resources/2_0/petstore-with-date-field.yaml
templateDir: src/main/resources/kotlin-client
additionalProperties:
  requestDateConverter: toString
  artifactId: kotlin-petstore-json-request-string
  parcelizeModels: true
  supportAndroidApiLevel25AndBelow: true
  serializationLibrary: kotlinx_serialization
  enumUnknownDefaultCase: "true"
