generatorName: kotlin-server
outputDir: samples/server/petstore/kotlin-server/jaxrs-spec
library: jaxrs-spec
inputSpec: src/test/resources/2_0/petstore.yaml
templateDir: src/main/resources/kotlin-server
additionalProperties:
  useCoroutines: "true"
