generatorName: kotlin
outputDir: samples/client/petstore/kotlin-moshi-codegen
inputSpec: src/test/resources/2_0/petstore.yaml
templateDir: src/main/resources/kotlin-client
additionalProperties:
  serializationLibrary: moshi
  artifactId: kotlin-petstore-moshi-codegen
  moshiCodeGen: "true"
