generatorName: kotlin-spring
outputDir: samples/server/petstore/kotlin-springboot-modelMutable
library: spring-boot
inputSpec: modules/openapi-json-schema-generator/src/test/resources/2_0/petstore.yaml
templateDir: modules/openapi-json-schema-generator/src/main/resources/kotlin-spring
additionalProperties:
  documentationProvider: springdoc
  annotationLibrary: swagger2
  useSwaggerUI: "true"
  serializableModel: "true"
  serviceImplementation: "true"
  beanValidations: "true"
  modelMutable: "true"
