generatorName: kotlin-spring
outputDir: samples/server/petstore/kotlin-springboot-springfox
library: spring-boot
inputSpec: src/test/resources/2_0/petstore.yaml
templateDir: src/main/resources/kotlin-spring
additionalProperties:
  documentationProvider: springfox
  annotationLibrary: swagger1
  useSwaggerUI: "true"
  serviceImplementation: "true"
  serializableModel: "true"
  beanValidations: "true"
