generatorName: kotlin-spring
outputDir: samples/server/petstore/kotlin-springboot-delegate
library: spring-boot
inputSpec: src/test/resources/3_0/petstore.yaml
templateDir: src/main/resources/kotlin-spring
additionalProperties:
  documentationProvider: springdoc
  annotationLibrary: swagger2
  useSwaggerUI: "true"
  delegatePattern: "true"
  beanValidations: "true"
