generatorName: kotlin
outputDir: samples/client/petstore/kotlin-nullable
inputSpec: src/test/resources/2_0/petstore.yaml
templateDir: src/main/resources/kotlin-client
additionalProperties:
  artifactId: kotlin-petstore-nullable
  serializableModel: "true"
  nullableReturnType: "true"
