generatorName: kotlin
outputDir: samples/client/petstore/kotlin-jvm-volley
library: jvm-volley
inputSpec: src/test/resources/2_0/petstore.yaml
templateDir: src/main/resources/kotlin-client
additionalProperties:
  artifactId: kotlin-petstore-jvm-volley
  generateRoomModels: "true"
  serializationLibrary: "gson"
