generatorName: kotlin
outputDir: samples/client/petstore/kotlin-gson
inputSpec: modules/openapi-json-schema-generator/src/test/resources/2_0/petstore.yaml
templateDir: modules/openapi-json-schema-generator/src/main/resources/kotlin-client
additionalProperties:
  serializationLibrary: gson
  artifactId: kotlin-petstore-gson
