generatorName: kotlin
outputDir: samples/client/petstore/kotlin-allOff-discriminator
inputSpec: src/test/resources/3_0/issue_10792.yaml
templateDir: src/main/resources/kotlin-client
additionalProperties:
  artifactId: kotlin-allOff-discriminator
  serializableModel: "false"
  dateLibrary: java8
  enumUnknownDefaultCase: true
