generatorName: kotlin-server
outputDir: samples/server/petstore/kotlin-server/jaxrs-spec
library: jaxrs-spec
inputSpec: modules/openapi-json-schema-generator/src/test/resources/2_0/petstore.yaml
templateDir: modules/openapi-json-schema-generator/src/main/resources/kotlin-server
additionalProperties:
  useCoroutines: "true"
