generatorName: kotlin
outputDir: samples/client/petstore/kotlin-jackson
inputSpec: modules/openapi-json-schema-generator/src/test/resources/2_0/petstore.yaml
templateDir: modules/openapi-json-schema-generator/src/main/resources/kotlin-client
additionalProperties:
  serializationLibrary: jackson
  artifactId: kotlin-petstore-jackson
  enumPropertyNaming: UPPERCASE
