generatorName: kotlin
outputDir: samples/client/petstore/kotlin-retrofit2
library: jvm-retrofit2
inputSpec: src/test/resources/2_0/petstore.yaml
templateDir: src/main/resources/kotlin-client
additionalProperties:
  artifactId: kotlin-petstore-retrofit2
