generatorName: kotlin
outputDir: samples/client/petstore/kotlin-bigdecimal-default-okhttp4
inputSpec: modules/openapi-json-schema-generator/src/test/resources/3_0/issue_10866_bigdecimal_default.yaml
templateDir: modules/openapi-json-schema-generator/src/main/resources/kotlin-client
additionalProperties:
  artifactId: kotlin-bigdecimal-default-okhttp4
  library: jvm-okhttp4
