generatorName: kotlin
outputDir: samples/client/petstore/kotlin-retrofit2-kotlinx_serialization
library: jvm-retrofit2
inputSpec: src/test/resources/2_0/petstore.yaml
templateDir: src/main/resources/kotlin-client
additionalProperties:
  serializationLibrary: kotlinx_serialization
  artifactId: kotlin-petstore-retrofit2-kotlinx_serialization
  enumPropertyNaming: UPPERCASE
  serializableModel: "true"
