generatorName: kotlin
outputDir: samples/client/petstore/kotlin-array-simple-string-jvm-volley
inputSpec: src/test/resources/3_0/issue_7199_array_simple_string.yaml
templateDir: src/main/resources/kotlin-client
additionalProperties:
  artifactId: kotlin-array-simple-string-jvm-volley
  library: jvm-volley
  serializationLibrary: gson
  generateRoomModels: false
