generatorName: kotlin-server
outputDir: samples/server/petstore/kotlin-server/ktor
library: ktor
inputSpec: src/test/resources/2_0/petstore.yaml
templateDir: src/main/resources/kotlin-server
additionalProperties:
  hideGenerationTimestamp: "true"
  serializableModel: "true"
