generatorName: kotlin
outputDir: samples/client/petstore/kotlin-gson
inputSpec: src/test/resources/2_0/petstore.yaml
templateDir: src/main/resources/kotlin-client
additionalProperties:
  serializationLibrary: gson
  artifactId: kotlin-petstore-gson
