generatorName: kotlin
outputDir: samples/client/petstore/kotlin-nullable
inputSpec: modules/openapi-json-schema-generator/src/test/resources/2_0/petstore.yaml
templateDir: modules/openapi-json-schema-generator/src/main/resources/kotlin-client
additionalProperties:
  artifactId: kotlin-petstore-nullable
  serializableModel: "true"
  nullableReturnType: "true"
