generatorName: kotlin-spring
outputDir: samples/server/petstore/kotlin-springboot-source-swagger2
library: spring-boot
inputSpec: src/test/resources/2_0/petstore.yaml
templateDir: src/main/resources/kotlin-spring
additionalProperties:
  documentationProvider: source
  annotationLibrary: swagger2
  useSwaggerUI: "true"
  serviceImplementation: "true"
  serializableModel: "true"
  beanValidations: "true"
