generatorName: kotlin
outputDir: samples/client/petstore/kotlin-jvm-okhttp4-coroutines
library: jvm-okhttp4
inputSpec: src/test/resources/2_0/petstore.yaml
templateDir: src/main/resources/kotlin-client
additionalProperties:
  serializationLibrary: gson
  useCoroutines: "true"
  artifactId: kotlin-petstore-okhttp4-coroutines-client
  serializableModel: "true"
  dateLibrary: java8
