generatorName: kotlin
outputDir: samples/client/petstore/kotlin-jvm-ktor-gson
library: jvm-ktor
inputSpec: src/test/resources/2_0/petstore.yaml
templateDir: src/main/resources/kotlin-client
additionalProperties:
  artifactId: kotlin-petstore-jvm-ktor-gson
  enumUnknownDefaultCase: true
  serializationLibrary: gson
