generatorName: kotlin-vertx
outputDir: samples/server/petstore/kotlin/vertx
inputSpec: modules/openapi-json-schema-generator/src/test/resources/2_0/petstore.yaml
templateDir: modules/openapi-json-schema-generator/src/main/resources/kotlin-vertx-server
additionalProperties:
  modelMutable: "false"
