generatorName: kotlin-server
outputDir: samples/server/petstore/kotlin-server-modelMutable
library: ktor
inputSpec: modules/openapi-json-schema-generator/src/test/resources/2_0/petstore.yaml
templateDir: modules/openapi-json-schema-generator/src/main/resources/kotlin-server
additionalProperties:
  hideGenerationTimestamp: "true"
  modelMutable: "true"
