generatorName: kotlin
outputDir: samples/client/petstore/kotlin-threetenbp
inputSpec: src/test/resources/2_0/petstore.yaml
templateDir: src/main/resources/kotlin-client
additionalProperties:
  artifactId: kotlin-petstore-threetenbp
  dateLibrary: threetenbp
