generatorName: kotlin
outputDir: samples/client/petstore/kotlin-string
inputSpec: src/test/resources/2_0/petstore.yaml
templateDir: src/main/resources/kotlin-client
additionalProperties:
  artifactId: kotlin-petstore-string
  serializableModel: "true"
  sortModelPropertiesByRequiredFlag: "false"
  sortParamsByRequiredFlag: "false"
  dateLibrary: string
