generatorName: kotlin
outputDir: samples/client/petstore/kotlin-nonpublic
inputSpec: src/test/resources/2_0/petstore.yaml
templateDir: src/main/resources/kotlin-client
additionalProperties:
  nonPublicApi: "true"
  artifactId: kotlin-petstore-nonpublic
