generatorName: ktorm-schema
outputDir: samples/schema/petstore/ktorm
inputSpec: modules/openapi-json-schema-generator/src/test/resources/3_0/petstore.yaml
templateDir: modules/openapi-json-schema-generator/src/main/resources/ktorm-schema
additionalProperties:
  hideGenerationTimestamp: true
  importModelPackageName: org.openapijsonschematools.client.models
