generatorName: mysql-schema
outputDir: samples/schema/petstore/mysql
inputSpec: src/test/resources/3_0/petstore-with-fake-endpoints-models-for-testing.yaml
templateDir: src/main/resources/mysql-schema
