generatorName: objc
outputDir: samples/client/petstore/objc/core-data
inputSpec: src/test/resources/3_0/petstore.json
templateDir: src/main/resources/objc
additionalProperties:
  classPrefix: SWG
  podName: SwaggerClient
  coreData: "true"
