generatorName: objc
outputDir: samples/client/petstore/objc/default
inputSpec: modules/openapi-json-schema-generator/src/test/resources/3_0/petstore.json
templateDir: modules/openapi-json-schema-generator/src/main/resources/objc
additionalProperties:
  classPrefix: SWG
  podName: SwaggerClient
