generatorName: ocaml
outputDir: samples/client/petstore/ocaml
inputSpec: src/test/resources/3_0/petstore.yaml
templateDir: src/main/resources/ocaml
additionalProperties:
  packageName: petstore_client
