generatorName: perl
outputDir: samples/client/petstore/perl
inputSpec: modules/openapi-json-schema-generator/src/test/resources/3_0/petstore-with-fake-endpoints-models-for-testing.yaml
templateDir: modules/openapi-json-schema-generator/src/main/resources/perl
additionalProperties:
  hideGenerationTimestamp: "true"
