generatorName: php-symfony
outputDir: samples/server/petstore/php-symfony/SymfonyBundle-php
inputSpec: modules/openapi-json-schema-generator/src/test/resources/3_0/petstore.yaml
templateDir: modules/openapi-json-schema-generator/src/main/resources/php-symfony
gitUserId: openapijsonschematools
gitRepoId: petstore
