generatorName: php-dt
outputDir: samples/client/petstore/php-dt-modern
inputSpec: src/test/resources/3_0/petstore.yaml
templateDir: src/main/resources/php-dt-modern
additionalProperties:
  modern: "true"
