generatorName: php-mezzio-ph
outputDir: samples/server/petstore/php-mezzio-ph-modern
inputSpec: src/test/resources/3_0/petstore.yaml
templateDir: src/main/resources/php-mezzio-ph-modern
additionalProperties:
  modern: "true"
