generatorName: php-dt
outputDir: samples/client/petstore/php-dt
inputSpec: modules/openapi-json-schema-generator/src/test/resources/3_0/petstore.yaml
templateDir: modules/openapi-json-schema-generator/src/main/resources/php-dt
