generatorName: php-laravel
outputDir: samples/server/petstore/php-laravel
inputSpec: src/test/resources/3_0/petstore-with-fake-endpoints-models-for-testing.yaml
templateDir: src/main/resources/php-laravel
gitUserId: openapijsonschematools
gitRepoId: petstore
