generatorName: php-laravel
outputDir: samples/server/petstore/php-laravel
inputSpec: modules/openapi-json-schema-generator/src/test/resources/3_0/petstore-with-fake-endpoints-models-for-testing.yaml
templateDir: modules/openapi-json-schema-generator/src/main/resources/php-laravel
gitUserId: openapijsonschematools
gitRepoId: petstore
