generatorName: protobuf-schema
outputDir: samples/config/petstore/protobuf-schema
inputSpec: modules/openapi-json-schema-generator/src/test/resources/3_0/protobuf/petstore.yaml
templateDir: modules/openapi-json-schema-generator/src/main/resources/protobuf-schema
additionalProperties:
  packageName: petstore
