generatorName: protobuf-schema
outputDir: samples/config/petstore/protobuf-schema
inputSpec: src/test/resources/3_0/protobuf/petstore.yaml
templateDir: src/main/resources/protobuf-schema
additionalProperties:
  packageName: petstore
