generatorName: python-aiohttp
outputDir: samples/server/petstore/python-aiohttp-srclayout
inputSpec: src/test/resources/2_0/petstore.yaml
templateDir: src/main/resources/python-aiohttp
additionalProperties:
  pythonSrcRoot: src
