generatorName: python-legacy
outputDir: samples/openapi3/client/petstore/python-legacy
inputSpec: src/test/resources/3_0/petstore-with-fake-endpoints-models-for-testing.yaml
templateDir: src/main/resources/python-legacy
additionalProperties:
  packageName: petstore_api
