generatorName: python
outputDir: samples/openapi3/client/features/dynamic-servers/python/
inputSpec: modules/openapi-json-schema-generator/src/test/resources/3_0/features/dynamic-servers.yaml
templateDir: modules/openapi-json-schema-generator/src/main/resources/python
additionalProperties:
  packageName: dynamic_servers
