generatorName: python-fastapi
outputDir: samples/server/petstore/python-fastapi
inputSpec: modules/openapi-json-schema-generator/src/test/resources/3_0/petstore.yaml
templateDir: modules/openapi-json-schema-generator/src/main/resources/python-fastapi
sourceFolder: "src"
additionalProperties:
  hideGenerationTimestamp: "true"
