generatorName: python-legacy
outputDir: samples/client/petstore/python-legacy
inputSpec: src/test/resources/2_0/petstore-with-fake-endpoints-models-for-testing.yaml
templateDir: src/main/resources/python-legacy
additionalProperties:
  packageName: petstore_api
