generatorName: python-prior
outputDir: samples/client/petstore/python-prior_disallowAdditionalPropertiesIfNotPresent
inputSpec: src/test/resources/2_0/python-prior/petstore-with-fake-endpoints-models-for-testing.yaml
templateDir: src/main/resources/python-prior
additionalProperties:
  disallowAdditionalPropertiesIfNotPresent: "true"
  packageName: petstore_api
