generatorName: python-prior
outputDir: samples/openapi3/client/extensions/x-auth-id-alias/python-prior/
inputSpec: modules/openapi-json-schema-generator/src/test/resources/3_0/extensions/x-auth-id-alias.yaml
templateDir: modules/openapi-json-schema-generator/src/main/resources/python
additionalProperties:
  packageName: x_auth_id_alias
