generatorName: r
outputDir: samples/client/petstore/R-httr2
inputSpec: src/test/resources/3_0/r/petstore.yaml
templateDir: src/main/resources/r
httpUserAgent: PetstoreAgent
library: httr2
additionalProperties:
  packageName: petstore
  exceptionPackage: rlang
  useRlangExceptionHandling: true
  returnExceptionOnFailure: true
  errorObjectType: "ModelApiResponse"
  operationIdNaming: snake_case
