generatorName: ruby
outputDir: samples/client/petstore/ruby-faraday
library: faraday
inputSpec: src/test/resources/3_0/petstore-with-fake-endpoints-models-for-testing.yaml
templateDir: src/main/resources/ruby-client
additionalProperties:
  gemVersion: 1.0.0
  moduleName: Petstore
  gemName: petstore
  skipFormModel: "true"
