generatorName: ruby
outputDir: samples/openapi3/client/features/dynamic-servers/ruby/
inputSpec: src/test/resources/3_0/features/dynamic-servers.yaml
templateDir: src/main/resources/ruby-client
additionalProperties:
  gemVersion: 1.0.0
  moduleName: DynamicServers
  gemName: dynamic_servers
  skipFormModel: "true"
