generatorName: rust-server
outputDir: samples/server/petstore/rust-server/output/ping-bearer-auth
inputSpec: src/test/resources/3_0/rust-server/ping-bearer-auth.yaml
templateDir: src/main/resources/rust-server
generateAliasAsModel: true
additionalProperties:
  hideGenerationTimestamp: "true"
  packageName: ping-bearer-auth
