generatorName: rust
outputDir: samples/client/petstore/rust/hyper/petstore
library: hyper
inputSpec: src/test/resources/3_0/rust/petstore.yaml
templateDir: src/main/resources/rust
additionalProperties:
  supportAsync: "false"
  packageName: petstore-hyper
