generatorName: rust
outputDir: samples/client/petstore/rust/reqwest/petstore
library: reqwest
inputSpec: src/test/resources/3_0/rust/petstore.yaml
templateDir: src/main/resources/rust
additionalProperties:
  supportAsync: false
  packageName: petstore-reqwest
