generatorName: rust-server
outputDir: samples/server/petstore/rust-server/output/multipart-v3
inputSpec: modules/openapi-json-schema-generator/src/test/resources/3_0/rust-server/multipart-v3.yaml
templateDir: modules/openapi-json-schema-generator/src/main/resources/rust-server
generateAliasAsModel: true
additionalProperties:
  hideGenerationTimestamp: "true"
  packageName: multipart-v3
