generatorName: rust-server
outputDir: samples/server/petstore/rust-server/output/rust-server-test
inputSpec: src/test/resources/2_0/rust-server/rust-server-test.yaml
templateDir: src/main/resources/rust-server
generateAliasAsModel: true
additionalProperties:
  hideGenerationTimestamp: "true"
  packageName: rust-server-test
