generatorName: rust
outputDir: samples/client/petstore/rust/reqwest/petstore-awsv4signature
library: reqwest
inputSpec: src/test/resources/3_0/rust/petstore.yaml
templateDir: src/main/resources/rust
additionalProperties:
  supportAsync: false
  packageName: petstore-reqwest-awsv4signature
  withAWSV4Signature: true
