generatorName: rust-server
outputDir: samples/server/petstore/rust-server/output/ops-v3
inputSpec: src/test/resources/3_0/rust-server/ops-v3.yaml
templateDir: src/main/resources/rust-server
generateAliasAsModel: true
additionalProperties:
  hideGenerationTimestamp: "true"
  packageName: ops-v3
