generatorName: scala-play-server
outputDir: samples/server/petstore/scala-play-server
inputSpec: src/test/resources/3_0/petstore.yaml
templateDir: src/main/resources/scala-play-server
additionalProperties:
  hideGenerationTimestamp: "true"
