generatorName: scala-akka
outputDir: samples/client/petstore/scala-akka
inputSpec: src/test/resources/3_0/scala-akka/petstore.yaml
templateDir: src/main/resources/scala-akka-client
additionalProperties:
  artifactId: scala-akka-petstore-client
