generatorName: scala-sttp
outputDir: samples/client/petstore/scala-sttp
inputSpec: src/test/resources/3_0/scala/petstore.yaml
templateDir: src/main/resources/scala-sttp
additionalProperties:
  artifactId: scala-sttp-petstore
