generatorName: scala-sttp
outputDir: samples/client/petstore/scala-sttp
inputSpec: modules/openapi-json-schema-generator/src/test/resources/3_0/scala/petstore.yaml
templateDir: modules/openapi-json-schema-generator/src/main/resources/scala-sttp
additionalProperties:
  artifactId: scala-sttp-petstore
