generatorName: scala-akka
outputDir: samples/client/petstore/scala-akka
inputSpec: modules/openapi-json-schema-generator/src/test/resources/3_0/scala-akka/petstore.yaml
templateDir: modules/openapi-json-schema-generator/src/main/resources/scala-akka-client
additionalProperties:
  artifactId: scala-akka-petstore-client
