# This is for generating scala legacy client
generatorName: scala-httpclient-deprecated
outputDir: samples/client/petstore/scala-httpclient-deprecated
inputSpec: modules/openapi-json-schema-generator/src/test/resources/3_0/petstore.yaml
templateDir: modules/openapi-json-schema-generator/src/main/resources/scala-httpclient
additionalProperties:
  apiPackage: org.openapijsonschematools.example.api
  invokerPackage: org.openapijsonschematools.example.invoker
  artifactId: scala-legacy-petstore