systemProperties:
  skipFormModel: "true"
generatorName: scala-lagom-server
outputDir: samples/server/petstore/scala-lagom-server
inputSpec: src/test/resources/3_0/petstore.yaml
templateDir: src/main/resources/scala-lagom-server
