generatorName: scala-play-server
outputDir: samples/server/petstore/scala-play-server
inputSpec: modules/openapi-json-schema-generator/src/test/resources/3_0/petstore.yaml
templateDir: modules/openapi-json-schema-generator/src/main/resources/scala-play-server
additionalProperties:
  hideGenerationTimestamp: "true"
