generatorName: spring
outputDir: samples/openapi3/client/petstore/spring-stubs-skip-default-interface
inputSpec: src/test/resources/2_0/petstore.yaml
templateDir: src/main/resources/JavaSpring
additionalProperties:
  groupId: org.openapijsonschematools.openapi3
  documentationProvider: springdoc
  artifactId: spring-stubs
  interfaceOnly: "true"
  unhandledException: true
  skipDefaultInterface: true
  singleContentTypes: "true"
  hideGenerationTimestamp: "true"
