generatorName: spring
outputDir: samples/server/petstore/springboot
inputSpec: src/test/resources/2_0/petstore-with-fake-endpoints-models-for-testing.yaml
templateDir: src/main/resources/JavaSpring
additionalProperties:
  documentationProvider: springfox
  artifactId: springboot
  snapshotVersion: "true"
  hideGenerationTimestamp: "true"
