generatorName: spring
outputDir: samples/openapi3/server/petstore/spring-boot-oneof
inputSpec: src/test/resources/3_0/oneof_polymorphism_and_inheritance.yaml
templateDir: src/main/resources/JavaSpring
additionalProperties:
  groupId: org.openapijsonschematools.openapi3
  documentationProvider: springdoc
  artifactId: springboot-oneof
  snapshotVersion: "true"
  hideGenerationTimestamp: "true"
