generatorName: spring
outputDir: samples/openapi3/server/petstore/springboot-useoptional
inputSpec: src/test/resources/2_0/petstore-with-fake-endpoints-models-for-testing.yaml
templateDir: src/main/resources/JavaSpring
additionalProperties:
  groupId: org.openapijsonschematools.openapi3
  documentationProvider: springdoc
  useOptional: true
  artifactId: spring-boot-useoptional
  hideGenerationTimestamp: "true"
