generatorName: spring
outputDir: samples/client/petstore/spring-cloud-feign-without-url
library: spring-cloud
inputSpec: modules/openapi-json-schema-generator/src/test/resources/3_0/petstore.yaml
templateDir: modules/openapi-json-schema-generator/src/main/resources/JavaSpring
additionalProperties:
  documentationProvider: springfox
  artifactId: petstore-spring-cloud
  hideGenerationTimestamp: "true"
  useFeignClientUrl: "false"
