generatorName: spring
outputDir: samples/server/petstore/springboot-spring-pageable-delegatePattern
library: spring-boot
inputSpec: src/test/resources/2_0/petstore-with-fake-endpoints-models-for-testing-with-spring-pageable.yaml
templateDir: src/main/resources/JavaSpring
delegatePattern: true
additionalProperties:
  documentationProvider: springfox
  artifactId: springboot-spring-pageable-delegatePattern
  hideGenerationTimestamp: 'true'
