generatorName: spring
outputDir: samples/openapi3/server/petstore/springboot-3
inputSpec: src/test/resources/3_0/petstore.yaml
templateDir: src/main/resources/JavaSpring
additionalProperties:
  groupId: org.openapijsonschematools.openapi3
  documentationProvider: springdoc
  artifactId: springboot
  snapshotVersion: "true"
  useSpringBoot3: true
  useBeanValidation: true
  hideGenerationTimestamp: "true"
