generatorName: spring
outputDir: samples/openapi3/client/petstore/spring-cloud-async
library: spring-cloud
inputSpec: src/test/resources/2_0/petstore.yaml
templateDir: src/main/resources/JavaSpring
additionalProperties:
  groupId: org.openapijsonschematools.openapi3
  documentationProvider: springdoc
  async: "true"
  java8: "true"
  artifactId: petstore-spring-cloud
  hideGenerationTimestamp: "true"
