generatorName: spring
outputDir: samples/openapi3/client/petstore/spring-cloud-spring-pageable
library: spring-cloud
inputSpec: src/test/resources/2_0/petstore-with-spring-pageable.yaml
templateDir: src/main/resources/JavaSpring
additionalProperties:
  groupId: org.openapijsonschematools.openapi3
  documentationProvider: springdoc
  artifactId: spring-cloud-spring-pageable
  hideGenerationTimestamp: 'true'
