generatorName: spring
library: spring-cloud
outputDir: samples/openapi3/client/petstore/spring-cloud-3
inputSpec: src/test/resources/3_0/petstore.yaml
templateDir: src/main/resources/JavaSpring
additionalProperties:
  groupId: org.openapijsonschematools.openapi3
  documentationProvider: springdoc
  artifactId: spring-cloud-oas3
  useSpringBoot3: "true"
  interfaceOnly: "true"
  singleContentTypes: "true"
  hideGenerationTimestamp: "true"
