generatorName: spring
outputDir: samples/server/petstore/springboot-beanvalidation
library: spring-boot
inputSpec: src/test/resources/2_0/petstore-with-fake-endpoints-models-for-testing.yaml
templateDir: src/main/resources/JavaSpring
additionalProperties:
  documentationProvider: springfox
  useSwaggerUI: false
  java8: true
  useBeanValidation: true
  artifactId: spring-boot-beanvalidation
  hideGenerationTimestamp: "true"
