generatorName: spring
outputDir: samples/server/petstore/springboot-delegate-j8
inputSpec: src/test/resources/2_0/petstore-with-fake-endpoints-models-for-testing.yaml
templateDir: src/main/resources/JavaSpring
additionalProperties:
  documentationProvider: springfox
  artifactId: springboot-delegate-j8
  hideGenerationTimestamp: "true"
  delegatePattern: "true"
