generatorName: spring
outputDir: samples/server/petstore/springboot-reactive
inputSpec: src/test/resources/2_0/petstore-with-fake-endpoints-models-for-testing.yaml
templateDir: src/main/resources/JavaSpring
additionalProperties:
  artifactId: springboot-reactive
  documentationProvider: springfox
  reactive: "true"
  hideGenerationTimestamp: "true"
  delegatePattern: "true"
