generatorName: spring
outputDir: samples/server/petstore/springboot-virtualan
library: spring-boot
inputSpec: src/test/resources/2_0/petstore-with-fake-endpoints-models-for-testing.yaml
templateDir: src/main/resources/JavaSpring
additionalProperties:
  documentationProvider: springdoc
  apiPackage: org.openapijsonschematools.virtualan.api
  modelPackage: org.openapijsonschematools.virtualan.model
  virtualService: true
  artifactId: springboot-virtualan
  hideGenerationTimestamp: "true"
