generatorName: spring
outputDir: samples/server/petstore/spring-stubs
inputSpec: src/test/resources/2_0/petstore.yaml
templateDir: src/main/resources/JavaSpring
additionalProperties:
  documentationProvider: springfox
  artifactId: spring-stubs
  interfaceOnly: "true"
  singleContentTypes: "true"
  hideGenerationTimestamp: "true"
