generatorName: spring
outputDir: samples/openapi3/server/petstore/springboot-delegate
inputSpec: src/test/resources/2_0/petstore-with-fake-endpoints-models-for-testing.yaml
templateDir: src/main/resources/JavaSpring
additionalProperties:
  groupId: org.openapijsonschematools.openapi3
  documentationProvider: springdoc
  artifactId: springboot-delegate
  hideGenerationTimestamp: "true"
  java8: true
  delegatePattern: "true"
