generatorName: spring
outputDir: samples/server/petstore/springboot-implicitHeaders-annotationLibrary
inputSpec: src/test/resources/3_0/petstore.yaml
templateDir: src/main/resources/JavaSpring
additionalProperties:
  artifactId: springboot-implicitHeaders-annotationLibrary
  documentationProvider: none
  annotationLibrary: none
  hideGenerationTimestamp: "true"
  implicitHeadersRegex: .*
