generatorName: spring
outputDir: samples/client/petstore/spring-cloud-spring-pageable
library: spring-cloud
inputSpec: src/test/resources/2_0/petstore-with-spring-pageable.yaml
templateDir: src/main/resources/JavaSpring
additionalProperties:
  documentationProvider: springfox
  artifactId: spring-cloud-spring-pageable
  hideGenerationTimestamp: 'true'
