generatorName: spring
outputDir: samples/openapi3/server/petstore/springboot-beanvalidation-no-nullable
library: spring-boot
inputSpec: src/test/resources/2_0/petstore-with-fake-endpoints-models-for-testing.yaml
templateDir: src/main/resources/JavaSpring
additionalProperties:
  groupId: org.openapijsonschematools.openapi3
  documentationProvider: springdoc
  java8: "false"
  useBeanValidation: true
  artifactId: spring-boot-beanvalidation-no-nullable
  hideGenerationTimestamp: "true"
  openApiNullable: "false"
