generatorName: spring
outputDir: samples/openapi3/server/petstore/spring-boot-springdoc
inputSpec: src/test/resources/3_0/petstore.yaml
templateDir: src/main/resources/JavaSpring
additionalProperties:
  groupId: org.openapijsonschematools.openapi3
  documentationProvider: springdoc
  useSwaggerUI: false
  artifactId: spring-boot-springdoc
  snapshotVersion: "true"
  hideGenerationTimestamp: "true"
