generatorName: spring
library: spring-cloud
outputDir: samples/openapi3/client/petstore/spring-cloud-date-time
inputSpec: src/test/resources/3_0/spring/date-time-parameter-types-for-testing.yml
templateDir: src/main/resources/JavaSpring
additionalProperties:
  groupId: org.openapijsonschematools.openapi3
  documentationProvider: springdoc
  artifactId: spring-cloud-date-time-oas3
  interfaceOnly: "true"
  singleContentTypes: "true"
  hideGenerationTimestamp: "true"