generatorName: spring
outputDir: samples/server/petstore/springboot-spring-pageable-without-j8
library: spring-boot
inputSpec: src/test/resources/2_0/petstore-with-fake-endpoints-models-for-testing-with-spring-pageable.yaml
templateDir: src/main/resources/JavaSpring
java8: false
additionalProperties:
  documentationProvider: springfox
  artifactId: springboot-spring-pageable-withoutj8
  hideGenerationTimestamp: 'true'
