generatorName: swift5
outputDir: samples/client/petstore/swift5/oneOf
inputSpec: src/test/resources/3_0/oneOf.yaml
templateDir: src/main/resources/swift5
generateAliasAsModel: true
additionalProperties:
  podAuthors: ""
  podSummary: PetstoreClient
  projectName: PetstoreClient
  podHomepage: https://github.com/openapi-json-schema-tools/openapi-json-schema-generator
