generatorName: swift5
outputDir: samples/client/petstore/swift5/resultLibrary
inputSpec: src/test/resources/2_0/swift/petstore-with-fake-endpoints-models-for-testing.yaml
templateDir: src/main/resources/swift5
generateAliasAsModel: true
additionalProperties:
  responseAs: Result
  podAuthors: ""
  podSummary: PetstoreClient
  projectName: PetstoreClient
  podHomepage: https://github.com/openapi-json-schema-tools/openapi-json-schema-generator
  removeMigrationProjectNameClass: true
