generatorName: swift5
outputDir: samples/client/petstore/swift5/default
inputSpec: modules/openapi-json-schema-generator/src/test/resources/2_0/petstore-with-fake-endpoints-models-for-testing.yaml
templateDir: modules/openapi-json-schema-generator/src/main/resources/swift5
generateAliasAsModel: true
additionalProperties:
  podAuthors: ""
  podSummary: PetstoreClient
  projectName: PetstoreClient
  podHomepage: https://github.com/openapi-json-schema-tools/openapi-json-schema-generator
