generatorName: typescript-axios
outputDir: samples/client/petstore/typescript-axios/builds/with-npm-version-and-separate-models-and-api
inputSpec: src/test/resources/2_0/petstore.yaml
templateDir: src/main/resources/typescript-axios
additionalProperties:
  npmVersion: 1.0.0
  apiPackage: api.another.level
  modelPackage: model.some.levels.deep
  withSeparateModelsAndApi: true
  npmName: '@openapijsonschematools/typescript-axios-petstore'
  npmRepository: https://skimdb.npmjs.com/registry
  snapshot: false
