generatorName: typescript-nestjs
outputDir: samples/client/petstore/typescript-nestjs-v8-provided-in-root/builds/default
inputSpec: src/test/resources/3_0/petstore.yaml
templateDir: src/main/resources/typescript-nestjs
additionalProperties:
  nestVersion: 8.0.0
  "npmName": "@openapijsonschematools/typescript-nestjs-petstore"
  "npmVersion": "1.0.0"
  "npmRepository" : "https://skimdb.npmjs.com/registry"
  "snapshot" : false
