generatorName: typescript
outputDir: samples/openapi3/client/petstore/typescript/builds/default
inputSpec: src/test/resources/3_0/petstore.yaml
templateDir: src/main/resources/typescript
additionalProperties:
  platform: node
  npmName: ts-petstore-client
  projectName: ts-petstore-client
  moduleName: petstore
