generatorName: typescript-axios
outputDir: samples/client/others/typescript-axios/with-separate-models-and-api-inheritance
inputSpec: src/test/resources/3_0/typescript-axios/with-separate-models-and-api-inheritance.yaml
templateDir: src/main/resources/typescript-axios
additionalProperties:
  apiPackage: api
  modelPackage: model
  withSeparateModelsAndApi: true
