generatorName: typescript-fetch
outputDir: samples/client/petstore/typescript-fetch/builds/prefix-parameter-interfaces
inputSpec: src/test/resources/2_0/petstore.yaml
templateDir: src/main/resources/typescript-fetch
additionalProperties:
  npmVersion: 1.0.0
  npmName: '@openapijsonschematools/typescript-fetch-petstore'
  npmRepository: https://skimdb.npmjs.com/registry
  prefixParameterInterfaces: true
  snapshot: false
