generatorName: typescript-axios
outputDir: samples/client/petstore/typescript-axios/builds/test-petstore
inputSpec: src/test/resources/3_0/java/petstore-with-fake-endpoints-models-for-testing-with-http-signature.yaml
templateDir: src/main/resources/typescript-axios