generatorName: typescript-axios
outputDir: samples/client/petstore/typescript-axios/builds/with-interfaces
inputSpec: src/test/resources/2_0/petstore.yaml
templateDir: src/main/resources/typescript-axios
additionalProperties:
  withInterfaces: "true"
