generatorName: typescript-fetch
outputDir: samples/client/petstore/typescript-fetch/builds/allOf-readonly
inputSpec: modules/openapi-json-schema-generator/src/test/resources/3_0/allOf-readonly.yaml
templateDir: modules/openapi-json-schema-generator/src/main/resources/typescript-fetch
