generatorName: typescript-angular
outputDir: samples/client/petstore/typescript-angular-v13-provided-in-any/builds/default
inputSpec: modules/openapi-json-schema-generator/src/test/resources/2_0/petstore.yaml
templateDir: modules/openapi-json-schema-generator/src/main/resources/typescript-angular
additionalProperties:
  ngVersion: 13.0.1
  providedIn: any
