generatorName: typescript-axios
outputDir: samples/client/petstore/typescript-axios/builds/es6-target
inputSpec: modules/openapi-json-schema-generator/src/test/resources/2_0/petstore.yaml
templateDir: modules/openapi-json-schema-generator/src/main/resources/typescript-axios
additionalProperties:
  npmVersion: 1.0.0
  supportsES6: true
  npmName: '@openapijsonschematools/typescript-axios-petstore'
  npmRepository: https://skimdb.npmjs.com/registry
  snapshot: false
