generatorName: typescript
outputDir: samples/openapi3/client/petstore/typescript/builds/composed-schemas
inputSpec: src/test/resources/3_0/composed-schemas.yaml
templateDir: src/main/resources/typescript
additionalProperties:
  npmName: ts-petstore-client
