generatorName: typescript-rxjs
outputDir: samples/client/petstore/typescript-rxjs/builds/with-npm-version
inputSpec: src/test/resources/2_0/petstore.yaml
templateDir: src/main/resources/typescript-rxjs
additionalProperties:
  npmVersion: 1.0.0
  npmName: '@openapijsonschematools/typescript-rxjs-petstore'
  npmRepository: https://skimdb.npmjs.com/registry
  snapshot: false
