generatorName: typescript-angular
outputDir: samples/client/petstore/typescript-angular-v12-provided-in-root/builds/with-npm
inputSpec: src/test/resources/2_0/petstore.yaml
templateDir: src/main/resources/typescript-angular
additionalProperties:
  ngVersion: 12.2.0
  npmVersion: 1.0.0
  npmName: '@openapijsonschematools/typescript-angular-petstore'
  npmRepository: https://skimdb.npmjs.com/registry
  snapshot: false
