generatorName: typescript-node
outputDir: samples/client/petstore/typescript-node/npm
inputSpec: modules/openapi-json-schema-generator/src/test/resources/2_0/petstore.yaml
templateDir: modules/openapi-json-schema-generator/src/main/resources/typescript-node
additionalProperties:
  npmVersion: 0.0.1
  npmName: '@openapijsonschematools/node-typescript-petstore'
  npmRepository: https://skimdb.npmjs.com/registry
  snapshot: false
