generatorName: typescript-angular
outputDir: samples/client/petstore/typescript-angular-v12-oneOf/builds/default
inputSpec: modules/openapi-json-schema-generator/src/test/resources/3_0/oneOfArrayMapImport.yaml
templateDir: modules/openapi-json-schema-generator/src/main/resources/typescript-angular
additionalProperties:
  ngVersion: 12.2.0
