generatorName: typescript-angular
outputDir: samples/client/petstore/typescript-angular-v13-provided-in-root/builds/with-npm
inputSpec: src/test/resources/3_0/petstore.yaml
templateDir: src/main/resources/typescript-angular
additionalProperties:
  ngVersion: 13.0.1
  npmVersion: 1.0.0
  npmName: '@openapijsonschematools/typescript-angular-petstore'
  npmRepository: https://skimdb.npmjs.com/registry
  snapshot: false
  supportsES6: true
