generatorName: typescript-angular
outputDir: samples/client/petstore/typescript-angular-v12-provided-in-root/builds/default
inputSpec: src/test/resources/2_0/petstore.yaml
templateDir: src/main/resources/typescript-angular
additionalProperties:
  ngVersion: 12.2.0
