generatorName: typescript-axios
outputDir: samples/client/petstore/typescript-axios/builds/with-node-imports
inputSpec: src/test/resources/2_0/petstore-with-operations-without-required-params.yaml
templateDir: src/main/resources/typescript-axios
additionalProperties:
  withNodeImports: "true"
  multipartFormData: "true"
