generatorName: typescript-fetch
outputDir: samples/client/petstore/typescript-fetch/builds/with-interfaces
inputSpec: modules/openapi-json-schema-generator/src/test/resources/2_0/petstore.yaml
templateDir: modules/openapi-json-schema-generator/src/main/resources/typescript-fetch
additionalProperties:
  withInterfaces: "true"
