generatorName: typescript-redux-query
outputDir: samples/client/petstore/typescript-redux-query/builds/default
inputSpec: src/test/resources/2_0/petstore.yaml
templateDir: src/main/resources/typescript-redux-query
