generatorName: typescript-angular
outputDir: samples/client/petstore/typescript-angular-v13-provided-in-root/builds/default
inputSpec: src/test/resources/3_0/petstore.yaml
templateDir: src/main/resources/typescript-angular
additionalProperties:
  ngVersion: 13.0.1
  supportsES6: true
