generatorName: typescript-fetch
outputDir: samples/client/petstore/typescript-fetch/builds/enum
inputSpec: src/test/resources/3_0/typescript-fetch/enum.yaml
templateDir: src/main/resources/typescript-fetch
