generatorName: typescript-axios
outputDir: samples/client/petstore/typescript-axios/builds/composed-schemas
inputSpec: modules/openapi-json-schema-generator/src/test/resources/3_0/composed-schemas.yaml
templateDir: modules/openapi-json-schema-generator/src/main/resources/typescript-axios
