generatorName: typescript
outputDir: samples/client/others/typescript/builds/with-unique-items
inputSpec: src/test/resources/3_0/typescript/unique_items.yaml
templateDir: src/main/resources/typescript
