generatorName: wsdl-schema
outputDir: samples/schema/petstore/wsdl-schema
inputSpec: modules/openapi-json-schema-generator/src/test/resources/3_0/wsdl/petstore.yaml
templateDir: modules/openapi-json-schema-generator/src/main/resources/wsdl-schema
additionalProperties:
  hideGenerationTimestamp: "true"
