generatorName: cpp-tizen
outputDir: samples/client/petstore/cpp-tizen
inputSpec: modules/openapi-json-schema-generator/src/test/resources/3_0/petstore.yaml
templateDir: modules/openapi-json-schema-generator/src/main/resources/cpp-tizen-client
