generatorName: elixir
outputDir: samples/client/petstore/elixir
inputSpec: modules/openapi-json-schema-generator/src/test/resources/3_0/petstore-with-fake-endpoints-models-for-testing.yaml
templateDir: modules/openapi-json-schema-generator/src/main/resources/elixir
