generatorName: go-gin-server
outputDir: samples/openapi3/server/petstore/go-gin-api-server
inputSpec: src/test/resources/3_0/petstore-with-fake-endpoints-models-for-testing.yaml
templateDir: src/main/resources/go-gin-server
additionalProperties:
  hideGenerationTimestamp: "true"
  packageName: petstoreserver
