generatorName: go-server
outputDir: samples/openapi3/server/petstore/go-api-server
inputSpec: src/test/resources/3_0/petstore-with-fake-endpoints-models-for-testing.yaml
templateDir: src/main/resources/go-server
additionalProperties:
  hideGenerationTimestamp: "true"
  packageName: petstoreserver
