generatorName: haskell-http-client
outputDir: samples/client/petstore/haskell-http-client
inputSpec: src/test/resources/3_0/petstore-with-fake-endpoints-models-for-testing.yaml
templateDir: src/main/resources/haskell-http-client
