generatorName: javascript-closure-angular
outputDir: samples/client/petstore/javascript-closure-angular
inputSpec: src/test/resources/3_0/petstore.yaml
templateDir: src/main/resources/Javascript-Closure-Angular
