generatorName: jaxrs-cxf-client
outputDir: samples/openapi3/client/petstore/jaxrs-cxf-client-jackson-nullable
inputSpec: src/test/resources/3_0/petstore-with-fake-endpoints-models-for-testing.yaml
templateDir: src/main/resources/JavaJaxRS/cxf
additionalProperties:
  jackson: "true"