generatorName: python-flask
outputDir: samples/openapi3/server/petstore/python-flask-python2
inputSpec: modules/openapi-json-schema-generator/src/test/resources/3_0/petstore-with-object-as-parameter.yaml
templateDir: modules/openapi-json-schema-generator/src/main/resources/python-flask
additionalProperties:
  supportPython2: true
