generatorName: python-flask
outputDir: samples/openapi3/server/petstore/python-flask
inputSpec: src/test/resources/3_0/petstore-with-object-as-parameter.yaml
templateDir: src/main/resources/python-flask
