generatorName: typescript-angular
outputDir: samples/client/petstore/typescript-angular/with-interfaces
inputSpec: src/test/resources/3_0/petstore.yaml
templateDir: src/main/resources/typescript-angular
additionalProperties:
  withInterfaces: "true"
  ngVersion: 13.3.2
