generatorName: typescript-angular
outputDir: samples/client/petstore/typescript-angular/default
inputSpec: src/test/resources/3_0/petstore.yaml
templateDir: src/main/resources/typescript-angular
additionalProperties:
  ngVersion: 13.3.2
