generatorName: typescript-fetch
outputDir: samples/client/petstore/typescript-fetch/builds/with-npm-version
inputSpec: modules/openapi-json-schema-generator/src/test/resources/3_0/petstore.yaml
templateDir: modules/openapi-json-schema-generator/src/main/resources/typescript-fetch
additionalProperties:
  npmVersion: 1.0.0
  npmName: '@openapijsonschematools/typescript-fetch-petstore'
  npmRepository: https://skimdb.npmjs.com/registry
  snapshot: false
