generatorName: python
outputDir: samples/openapi3/client/features/nonCompliantUseDiscriminatorIfCompositionFails/python
inputSpec: src/test/resources/3_0/nonCompliantUseDiscriminatorIfCompositionFails.yaml
additionalProperties:
  packageName: this_package
  nonCompliantUseDiscriminatorIfCompositionFails: true
