generatorName: python
outputDir: samples/openapi3/client/3_0_3_unit_test/python
inputSpec: src/test/resources/3_0/unit_test_spec/3_0_3_unit_test_spec.yaml
additionalProperties:
  packageName: unit_test_api
